travis:
  secure:
    BINSTAR_TOKEN: wFKabFU4f+c7dVhO7SyJgJb4oYNRAL6I2SrNI5o7ZF07m3Lcj95Dju1eXoG0f3hECVyMZjXCNUs/a93otnJgjL+bHIAZqsLsOkvbKyoq1fjKZidGRCJEhwBesa7jbDSTTGRn5jci0slr/tu3HlF3uM39TijyNC8qVa5DSH7qQSxuEdJxgIU7+hSGIw5z0sBJ8gLGbGSScAecfKrk1hVYt1mmD7GJ/1kfcPKka0DnJjUD3J1v5ffHjy6/+FNlvo6tR7TKfD0ZawB7KvZ3Jt1Qr7JSR2N/QVW6cF8ymkqx0cPv9DZeL7XhUJVG5HPgHkXh5VxEZwWBLc/j41vk6uqp6YcRoVaegueMQNJPUHHhafism3dSVwHMyOnF1TJ4mpwLy+9zdlDyyIbiyouSf1hLDwfRvjNxN2BwKgAz4BusVrK8Y7tvcNhOOd4PMV3uxIA33Dv5kXlANE+q+VK5SGPqODxs/JEPSiDXF7jFFvnhNntxqT/Y9S2YoullsheVJgkBCBEUuPgTn1DrhhyRC8z1I/mOSMjNKraYDOgFzAWchOJIUoBSI40ZfJjH0GR7X762uMQI+whYzIGQQDAoXsAZJ0cbZ4yZzLg3AjF1Q9FZiBpJTkgFJtNwF4StGvMHv+kO4aU+glrAI/CLN8AR8o6yqtT+UEwVg9N8mxfDhdchZMg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
